home/urls.py
from django.conf.urls import url
from home import views

app_name = 'home'

urlpatterns = [
    url(r'^$',views.HomeView.as_view(),name='index'),
]

lunch_box/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from home.views import HomeView

urlpatterns = [
    url(r'^$',HomeView.as_view(),name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^home/',include('home.urls')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^reservation/',include('reservation.urls')),
]

reservation/urls.py
from django.conf.urls import url
from reservation import views
from django.contrib.auth.decorators import login_required

app_name = 'reservation'

urlpatterns = [
    url(r'^$', login_required(views.ReservationListView.as_view()), name='list'),
    url(r'^create/$', login_required(views.ReservationCreate.as_view()), name='create'),
    url(r'^edit/(?P<pk>\d+)/$', login_required(views.ReservationUpdate.as_view()), name='update'),
    url(r'^delete/(?P<pk>\d+)/$', login_required(views.ReservationDelete.as_view()), name='delete'),
    url(r'^order/list/$', login_required(views.OrderListView.as_view()), name='order-list'),
    url(r'^order/create/$', login_required(views.OrderCreate.as_view()), name='order-create'),
    url(r'^order/edit/(?P<pk>\d+)/$', login_required(views.OrderUpdate.as_view()), name='order-update'),
    url(r'^order/delete/(?P<pk>\d+)/$', login_required(views.OrderDelete.as_view()), name='order-delete'),
]

home/models.py
from django.db import models
from django.contrib.auth.models import User

class Address(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,primary_key=True)
    address = models.TextField(max_length=256)
    subdistrict = models.CharField(max_length=256)
    district = models.CharField(max_length=256)
    province = models.CharField(max_length=256)

    def __str__(self):
        return str(self.user) + " : address" + ("\n%s\n%s\n%s\n%s\n" % (self.address,self.subdistrict,self.district,self.province))

reservation/models.py
from django.db import models
from django.contrib.auth.models import User

class ReservationData(models.Model):
    seat = models.PositiveIntegerField(default=1)
    reserved_time = models.DateTimeField('reserved_time',help_text="Please fill in YYYY-MM-DD HH:MM format")
    reserved_by = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        ordering = ('reserved_time',)

    def __str__(self):
        return "Reserve by :" + self.reserved_by.username


class Menu(models.Model):
    name = models.CharField(max_length=120, db_index=True,unique=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name


class OrderMenu(models.Model):
    quantity = models.PositiveIntegerField(default=1)
    menu_name = models.ForeignKey(Menu,on_delete=models.CASCADE)
    reservation = models.ForeignKey(ReservationData, on_delete=models.CASCADE)

    def __str__(self):
        return ("Ordered By : %s\nMenu : %s\nQuantity : %d\n" %(self.reservation.reserved_by.username,self.menu_name.name,self.quantity))

    def get_cost(self):
        return self.menu_name.price * self.quantity

home/views.py
from django.views.generic.base import TemplateView

class HomeView(TemplateView):
    template_name = 'home/index.html'

reservation/views.py
from django.views.generic.edit import CreateView,DeleteView,UpdateView
from django.views.generic import ListView
from .models import ReservationData,OrderMenu
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import redirect


#List all reservations
class ReservationListView(ListView):
    login_url = reverse_lazy('auth_login')
    model = ReservationData
    template_name = 'reservation/reservation_list.html'
    context_object_name = 'reservations'

    def get(self, request, *args, **kwargs):
        print(request.user.is_authenticated)
        if not request.user.is_authenticated:
            return redirect(self.login_url)
        else :
            response = super(ReservationListView, self).get(request=request,kwargs=kwargs)
            return response

    def get_queryset(self):
        username = self.request.user
        return ReservationData.objects.filter(reserved_by=username)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['reservation_edit_form'] = ReservationUpdate(request=self.request).get_form()
        return context

#Create a reservation
class ReservationCreate(CreateView):
    model = ReservationData
    fields = ['seat','reserved_time']
    template_name = 'reservation/reservation_create.html'

    def form_valid(self, form):
        new_reservation = form.save(commit=False)
        print(new_reservation.reserved_time.date()," : ",new_reservation.reserved_time.time())
        new_reservation.reserved_by = self.request.user
        new_reservation.save()
        self.request.session['reservation_id'] = new_reservation.id
        return redirect(reverse_lazy('reservation:order-list'))

#Delete a reservation
class ReservationDelete(DeleteView):
    model = ReservationData
    success_url = reverse_lazy('reservation:list')

#Update a reservation
class ReservationUpdate(UpdateView):
    model = ReservationData
    fields = ['seat','reserved_time']
    success_url = reverse_lazy('reservation:list')

#List all orders
class OrderListView(ListView):
    model = OrderMenu
    context_object_name = 'orders'
    template_name = 'reservation/order_list.html'
    
    def get_context_data(self, **kwargs):
        context = OrderMenu.objects.filter(reservation=ReservationData.objects.get(id=self.request.session['reservation_id']))
        context = {'orders':context}
        total_cost = sum([order.get_cost() for order in context['orders']])
        total_quantity = sum([order.quantity for order in context['orders']])
        context['total_quantity'] = total_quantity
        context['total_cost'] = total_cost
        context['order_create_form'] = OrderCreate(request=self.request).get_form()
        context['order_edit_form'] = OrderUpdate(request=self.request).get_form()
        return context

#Create a new order
class OrderCreate(CreateView):
    model = OrderMenu
    context_object_name = 'form'
    fields = ['quantity','menu_name']
    success_url = reverse_lazy('reservation:order-list')

    def get_context_data(self, **kwargs):
        context = super(OrderCreate, self).get_context_data(**kwargs)
        context['reservation_id'] = self.request.session['reservation_id']
        return context

    def form_valid(self, form):
        new_order = form.save(commit=False)
        print("Reservation id : ")
        new_order.reservation = ReservationData.objects.get(id=self.request.session['reservation_id'])
        new_order.save()
        return redirect(self.success_url)

#Update an order
class OrderUpdate(UpdateView):
    model = OrderMenu
    fields = ['quantity','menu_name']
    success_url = reverse_lazy('reservation:order-list')

#Delete an order
class OrderDelete(DeleteView):
    model = OrderMenu
    success_url = reverse_lazy('reservation:order-list')

templates/base.html
<!DOCTYPE html>
<html>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta {% block meta %}{% endblock meta %}>
  {% block title %} {% endblock title %}

  {% block style %}

  {% endblock style %}

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
</head>

<body>
    {% include 'header.html' %}

	{% block content %}

	{% endblock %}

    {% block javascript %}

    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
</body>
</html>

templates/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'home:index'%}">Reserve Hub</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home:index'%}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'reservation:list'%}">Reservation<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'registration_register'%}">Register<span class="sr-only">(current)</span></a>
        </li>
      </ul>
        {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'auth_logout' %}">Logout</a>
            <a class="navbar-text"><strong>Login as {{ user.get_username }}</strong></a>
        {% else %}
            <a class="nav-link" href="{% url 'auth_login'%}">Login</a>
        {% endif %}
    </div>
  </nav>

templates/home/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}<title>Index</title>{% endblock title %}

{% block style %}
    <style>
        body {
            background-image: url({% static 'img/home_cover.jpg' %});
            background-size: cover;
            background-attachment: fixed;
        }

        #feature {
            text-align: center;
            padding: 10% 0;
        }

        #main_display {
            padding: 16% 0;
            background-attachment: fixed;
            background-size: cover;
            text-align: center;
            letter-spacing: 3px;
        }

        #main_display div {
            margin: 1% 0;
            color: rgba(255, 240, 255, 0.9);
            text-shadow: 2px 2px 30px grey;
        }

        #main_display h1 {
            text-align: center;
            font-size: 3em;
            color: white;
            text-shadow: 2px 2px 30px black;
        }

        #step_1 {
            background-color: rgba(255,255,255,0.8);
            text-align: right;
        }

        #step_1 div:nth-child(1) {
            background-image: url({% static 'img/step_1.jpeg' %});
            background-size: cover;
            box-shadow: 2px 2px 30px grey;
            padding: 15% 0;
            margin: 3% 3% 3% 10%;
        }

        #step_1 div:nth-child(2) {
            padding: 15% 0;
            margin: 0 15% 0 0;
        }

        .black-space {
            padding: 10% 0;
        }

         #step_2 {
             text-align: left;
             background-color: rgba(255,255,255,0.8);
        }

        #step_2 div:nth-child(2) {
            background-image: url({% static 'img/step_2.jpeg' %});
            background-size: cover;
            box-shadow: 2px 2px 30px grey;
            padding: 14.5% 0;
            margin: 3% 10% 3% 3%;
        }

        #step_2 div:nth-child(1) {
            padding: 15% 0;
            margin: 0 0 0 15%;
        }

         #step_1 {
            background-color: rgba(255,255,255,0.8);
            text-align: right;
        }

        #step_3 {
            background-color: rgba(255,255,255,0.8);
            text-align: right;
        }


        #step_3 div:nth-child(1) {
            background-image: url({% static 'img/step_3.jpeg' %});
            background-size: cover;
            box-shadow: 2px 2px 30px grey;
            padding: 15% 0;
            margin: 3% 3% 3% 10%;
        }

        #step_3 div:nth-child(2) {
            padding: 15% 0;
            margin: 0 15% 0 0;
        }

    </style>
{% endblock style %}

{% block content %}
    <div class="container-fluid">
        <div class="row" id="main_display">
            <div class="col-md-12">
                <h1>THE RESERVE HUB</h1>
            </div>

        </div>
        <div class="row" id="step_1">
            <div class="col">

            </div>
            <div class="col">
                <h1>Make a reservation</h1>
                <h4>Reserve your seat <br> and set your arrival time.</h4>
            </div>
        </div>

        <div class="black-space row"></div>

        <div class="row" id="step_2">
            <div class="col">
                <h1>Place your orders</h1>
                <h4>Make your choices from our menu.<br>Let's fullfill your needs.</h4>
            </div>
             <div class="col">

            </div>
        </div>
        <div class="black-space row">

        </div>
        <div class="row" id="step_3">
            <div class="col">

            </div>
            <div class="col">
                <h1>Finish</h1>
                <h4>All is reserved for you<br>Please be on time and enjoy you meal</h4>
                <a href="{% url 'reservation:list' %}" class="btn btn-primary btn-lg">Get started</a>
            </div>
        </div>

    </div>
{% endblock %}

templates/reservation/order_list.html
{% extends 'base.html' %}
{% load bootstrap %}
{% load staticfiles %}
{#Title#}
{% block title %}
    <title>Reservation</title>
{% endblock %}

{#Style#}
{% block style %}
    <style media="screen">
        .wrapper {
            padding: 3%;
            margin-top: 5%;
            background-color: rgba(255,255,255,0.9);
        }
        @keyframes fadein {
            from {
                opacity: 0;
            }
            to {
                opacity: 1;
            }
        }
        body {
            background-image: url({% static 'img/home_cover.jpg' %});
            background-size: cover;
            background-attachment: fixed;
        }

        .wrapper div:nth-child(3) {
            margin-top: 6%;
        }

    </style>
{% endblock %}

{#Content#}
{% block content %}
    <div class="container">
       <div class="wrapper">
           <div class="row">
               <h1>Orders list</h1>
           </div>
           <div class="row">
               <table class="table">
                   <thead class="thead-dark">
                   <tr>
                       <th scope="col">Menu name</th>
                       <th scope="col">Quantity</th>
                       <th scope="col">Cost</th>
                       <th></th>
                       <th></th>
                   </tr>
                   </thead>
                   <tbody>
                   {% for order in orders %}
                       <tr>
                           <td>{{ order.menu_name }}</td>
                           <td>{{ order.quantity }}</td>
                           <td>{{ order.get_cost }}</td>
                           <td>
                               <button type="button" class="btn btn-warning col" data-toggle="modal" data-target="#editModal">
                                   Edit
                               </button>
                               <div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
                                   <div class="modal-dialog" role="document">
                                       <div class="modal-content">
                                           <div class="modal-header">
                                               <h5 class="modal-title" id="editModalLabel">Edit</h5>
                                               <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                   <span aria-hidden="true">&times;</span>
                                               </button>
                                           </div>
                                           <form method="POST" action="{% url 'reservation:order-update' order.id %}">
                                               {% csrf_token %}
                                               <div class="modal-body">
                                                   {{ order_edit_form | bootstrap }}
                                               </div>
                                               <div class="modal-footer">
                                                   <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                   <button type="submit" class="btn btn-primary">Save changes</button>
                                               </div>
                                           </form>
                                       </div>
                                   </div>
                               </div>
                           </td>
                           <td>
                               <button type="button" class="btn btn-danger col" data-toggle="modal" data-target="#deleteModal">
                                   Delete
                               </button>
                               <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
                                   <div class="modal-dialog" role="document">
                                       <div class="modal-content">
                                           <div class="modal-header">
                                               <h5 class="modal-title" id="editModalLabel">Delete</h5>
                                               <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                   <span aria-hidden="true">&times;</span>
                                               </button>
                                           </div>
                                           <form method="POST" action="{% url 'reservation:order-delete' order.id %}">
                                               {% csrf_token %}
                                               <div class="modal-body">
                                                   <h6>Are you sure you wanted to delete this order?</h6>
                                               </div>
                                               <div class="modal-footer">
                                                   <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                   <button type="submit" class="btn btn-danger">Delete</button>
                                               </div>
                                           </form>
                                       </div>
                                   </div>
                               </div>
                           </td>
                       </tr>
                   {% empty %}
                       <td colspan="6" class="text-center bg-warning">No Order Placed</td>
                   {% endfor %}

                   </tbody>
                   <tfoot class="thead-dark">
                   {% if orders %}
                       <td>Total</td>
                       <td>{{ total_quantity }}</td>
                       <td>{{ total_cost }}</td>
                       <td></td>
                       <td></td>
                   {% endif %}
                   </tfoot>
               </table>

           </div>
           <div class="row">
               <button type="button" class="btn btn-outline-secondary col-3" data-toggle="modal" data-target="#createModal">
                   Add new order
               </button>
               <div class="modal fade" id="createModal" tabindex="-1" role="dialog" aria-labelledby="createModalLabel" aria-hidden="true">
                   <div class="modal-dialog" role="document">
                       <div class="modal-content">
                           <div class="modal-header">
                               <h5 class="modal-title" id="createModalLabel">Edit</h5>
                               <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                   <span aria-hidden="true">&times;</span>
                               </button>
                           </div>
                           <form method="POST" action="{% url 'reservation:order-create'%}">
                               {% csrf_token %}
                               <div class="modal-body">
                                   {{ order_edit_form | bootstrap }}
                               </div>
                               <div class="modal-footer">
                                   <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                   <button type="submit" class="btn btn-primary">Add</button>
                               </div>
                           </form>
                       </div>
                   </div>
               </div>
               <a class="btn btn-primary offset-6 col-3" href="{% url 'reservation:list'%}">Finish</a>
           </div>
       </div>
    </div>
{% endblock %}

{#Javascript#}
{% block javascript %}

{% endblock %}

templates/reservation/reservation_create.html
{% extends 'base.html' %}
{% load bootstrap %}
{% load widget_tweaks %}
{% load staticfiles %}
{#Title#}
{% block title %}
    <title>Make a Reservation</title>
{% endblock %}

{#Style#}
{% block style %}

 <style>
    a {
        text-decoration: none;
    }
    .wrapper {
        padding: 3%;
        margin-top: 5%;
        background-color: rgba(255,255,255,0.9);
        animation: fadein 1s;
    }
    @keyframes fadein {
        from {
            opacity: 0;
        }
        to {
            opacity: 1;
        }
    }
    body {
        background-image: url({% static 'img/home_cover.jpg' %});
        background-size: cover;
        background-attachment: fixed;
    }
 </style>
    {{ form.media }}
{% endblock %}


{#Content#}
{% block content %}
    <div class="container">
        <div class="wrapper">
            <h1>New Reservation</h1>
            <form method="POST">
                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}

                {% for field in form.visible_fields %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field | add_class:'form-control'}}
                        {% for error in field.errors %}
                            <span class="help-block">{{ error }} <br></span>
                        {% endfor %}
                    </div>
                {% endfor %}
                <p class="help-block'">Please fill in YYYY-MM-DD HH:MM format</p>
                <button type="submit" class="btn btn-primary">Reserve</button>
            </form>
        </div>
    </div>
{% endblock %}

{#Javascript#}
{% block javascript %}

{% endblock %}

templates/reservation/reservation_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap %}
{#Title#}
{% block title %}
    <title>Reservation</title>
{% endblock %}

{#Style#}
{% block style %}
    <style media="screen">
        .wrapper {
            padding: 3%;
            margin-top: 5%;
            background-color: rgba(255,255,255,0.9);
            animation: fadein 1s;
        }
        @keyframes fadein {
            from {
                opacity: 0;
            }
            to {
                opacity: 1;
            }
        }
        body {
            background-image: url({% static 'img/home_cover.jpg' %});
            background-size: cover;
            background-attachment: fixed;
        }

        .wrapper div:nth-child(3) {
            margin-top: 6%;
        }

    </style>
{% endblock %}


{#Content#}
{% block content %}
    <div class="container">
        <div class="wrapper">
            <div class="row">
                <h1>Reservation List</h1>
            </div>
            <div class="row">
                <table class="table">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col">Reservation Id</th>
                        <th scope="col">Time</th>
                        <th scope="col">Date</th>
                        <th scope="col">Seat</th>
                        <th></th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for reservation in reservations %}
                        <tr>
                            <td>{{ reservation.id }}</td>
                            <td>{{ reservation.reserved_time.time }}</td>
                            <td>{{ reservation.reserved_time.date }}</td>
                            <td>{{ reservation.seat }}</td>
                            <td>
                                <button type="button" class="btn btn-warning col" data-toggle="modal" data-target="#editModal">
                                    Edit
                                </button>
                                <div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="editModalLabel">Edit</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <form method="POST" action="{% url 'reservation:update' reservation.id %}">
                                                {% csrf_token %}
                                                <div class="modal-body">
                                                    {{ reservation_edit_form | bootstrap }}
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                    <button type="submit" class="btn btn-primary">Save changes</button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </td>
                            <td>
                                <button type="button" class="btn btn-danger col" data-toggle="modal" data-target="#deleteModal">
                                    Delete
                                </button>
                                <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="editModalLabel">Delete</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <form method="POST" action="{% url 'reservation:delete' reservation.id %}">
                                                {% csrf_token %}
                                                <div class="modal-body">
                                                    <h5>Are you sure you wanted to delete this reservation ?</h5>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                    <button type="submit" class="btn btn-danger">Delete</button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% empty %}
                        <td colspan="6" class="text-center bg-warning">No Reservation</td>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="row">
                <a class="btn btn-primary" href="{% url 'reservation:create' %}">Make a Reservation</a>
            </div>
        </div>
    </div>

{% endblock %}

{#Javascript#}
{% block javascript %}

{% endblock %}